### PR TITLE
solve height width when image is rectangular

### PR DESCRIPTION
**Pull request by lingr7**
Testing noisy_img with a rectangular gray image
test_gray.png from Bing wallpaper 20200615
imageonline-co-grayscaledimage

```python
# -*- coding: utf-8 -*-
"""
Created on Sun Jun 14 21:42:25 2020

@author: ligong
"""
import numpy as np
import cv2
import matplotlib.image as io
from pyldpc import make_ldpc, ldpc_images
from pyldpc.utils_img import gray2bin, rgb2bin
from pyldpc import utils
from matplotlib import pyplot as plt
from PIL import Image

from time import time

eye = Image.open("data/test_gray.png")
plt.imshow(eye,'gray')
plt.show()

eye = np.asarray(eye.convert('LA'))[:, :, 0]

eye_bin = gray2bin(eye)
print("Eye shape: (%s, %s)" % eye.shape)
print("Binary Eye shape: (%s, %s, %s)" % eye_bin.shape)
n = 200
d_v = 3
d_c = 4
seed = 42

##################################################################
# First we create a small LDPC code i.e a pair of decoding and coding matrices
# H and G. H is a regular parity-check matrix with d_v ones per row
# and d_c ones per column

H, G = make_ldpc(n, d_v, d_c, seed=seed, systematic=True, sparse=True)

##################################################################
# Now we simulate the transmission with Gaussian white noise
# and recover the original image via belief-propagation.

snr = 8
eye_coded, eye_noisy = ldpc_images.encode_img(G, eye_bin, snr, seed=seed)
outFile_coded = "data/test_gray_coded.png"
outFile_noisy = "data/test_gray_noisy.png"
# io.imsave(outFile_noisy,eye_noisy)
plt.imshow(eye_noisy,'gray')
plt.show()
plt.imshow(eye_coded,'gray')
cv2.imwrite(outFile_noisy,eye_noisy)
cv2.imwrite(outFile_coded,eye_coded)
plt.show()
```

### CODE REVIEW

**Comment by hichamjanati** [comment]
Indeed, thanks a lot @lingr7 :) 
Would like to add your example to the documentation ? if so you can name it with a `plot_` prefix and put it in the examples folder. 
Or I can merge this

**Comment by lingr7** [comment]
The commit only exchanges the order of height width parameter transfer, because the square image exchange has no effect, but in order to correctly read out the image information (take out the information bits from the coding), the rectangle needs to exchange. The code given in my description validates the effect of the modification.
image

**Comment by lingr7** [comment]
I do it.

**Review by hichamjanati — APPROVED** [review]

**Comment by hichamjanati** [comment]
Thanks @lingr7

**Pull request merged**
